export const copy = {
  title: 'Rośliny dla kota',
  closeButtonAlt: 'zamknij',
  dangerHeadline: 'Zagrożenie',
  symptomsHeadline: 'Objawy',
  sourcesHeadline: 'Zweryfikuj informacje',
  otherNamesHeadline: 'Inne nazwy',
  copyrightsHeadline: 'Zdjęcie',
  plantSingularNominative: 'roślinę',
  plantPluralNominative: 'rośliny',
  plantPluralGenitive: 'roślin',
  toxicFilterLabel: 'Trujące',
  safeFilterLabel: 'Bezpieczne',
  safetyBadgeAlt: 'Zagrożenie',
  safePlantLabel: 'Bezpieczna',
  slightlyToxicPlantLabel: 'Lekko trująca',
  toxicPlantLabel: 'Trująca',
  highlyToxicPlantLabel: 'Silnie trująca',
  mainPageNav: 'Rośliny',
  blogPageNav: 'Blog',
  sortAscending: 'Po nazwie rosnąco',
  sortDescending: 'Po nazwie malejąco',
  footer: 'Anna Wróbel 🌱',
  whatNowHeadline: 'Twój kot to zjadł?',
  whatNowDesc: 'Dowiedz się, [html]co zrobić.[html]',
  symptomsIconAlt: 'Przewiń do sekcji: Objawy',
  whatNowIconAlt: 'Przewiń do sekcji: Co zrobić',
  sourcesIconAlt: 'Przewiń do sekcji: Zweryfikuj informacje',
};

export default copy;
